config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#homepage'

  resources :contacts, only: [:new, :create]

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'services' => 'static_pages#services'
  get 'portfolio' => 'static_pages#portfolio'

end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,     :validate => true
  attribute :email,    :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,  :validate => true
  attribute :nickname, :captcha => true

  def headers
    {
      :subject => "Scooter Envy Inquiry",
      :to => "scooterenvydesigns@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Could not end message.'
      render :new
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

def homepage
end

def about
end

def contact
end

def services
end

def portfolio
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/create.html.erb
<%= render :partial => "static_pages/navbar" %>

<div class="green_ribbon animated fadeIn">
  <div class="text_wrapper_large">
    <p class="subheading">Thank you for your message.  We'll get back to you as soon as possible!</p>
  </div>
</div>

app/views/contacts/new.html.erb
<%= render :partial => "static_pages/navbar" %>

<div class="green_ribbon animated fadeIn">
  <div class="text_wrapper_large">
    <p class="subheading">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
  </div>
</div>

<div id="contact_form" class="animated fadeIn">
  <%= form_for @contact do |f| %>
    <h4><%= f.label :name, "What's your name?", class:'contact_form_title' %></h4>
    <%= f.text_field :name, required: true, placeholder:'name', autofocus: true %>

    <h4><%= f.label :email, "How can we reach you?", class:'contact_form_title' %></h4>
    <%= f.email_field :email, required: true, placeholder:'email' %>

    <h4><%= f.label :message, "What can we do for you?", class:'contact_form_title' %></h4>
    <%= f.text_area :message, required: true, as: :text, placeholder:'message' %>
    <div class='hidden'> 
      <%= f.label :nickname %><br>
      <%= f.text_field :nickname, hint: 'leave this blank' %>
    </div>
    <br>
    <%= f.submit 'send', id:'send_button' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ScooterEnvyDesigns</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://use.typekit.net/byb3bon.js"></script>
  <script>try{Typekit.load({ async: true });}catch(e){}</script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/static_pages/_navbar.html.erb
<div>
  <ul class="navbar animated fadeInRight fadeIn">
    <% home = image_tag('scooter_only.png', id:'scooter_only') %>
    <%= link_to home, root_path %>
    <li class="nav_links <%= 'active' if current_page?(about_path)%>"><%= link_to 'About', about_path %></li>
    <li class="nav_links <%= 'active' if current_page?(services_path)%>"><%= link_to 'Services', services_path %></li>
    <li class="nav_links <%= 'active' if current_page?(portfolio_path)%>"><%= link_to 'Portfolio', portfolio_path %></li>
    <li class="nav_links <%= 'active' if current_page?(new_contact_path)%>"><%= link_to 'Contact', new_contact_path %></li>
  </ul>
</div>

app/views/static_pages/about.html.erb
<%= render 'navbar' %>

<div class="green_ribbon animated fadeIn">
  <div class="text_wrapper_large">
    <p class="subheading">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
  </div>
</div>

<div class="two_column_wrapper animated fadeIn">
  <p>Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Gallia est omnis divisa in partes tres, quarum. Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Quisque placerat facilisis egestas cillum dolore.<br>Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Quisque placerat facilisis egestas cillum dolore.</p>
  <p>Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ab illo tempore, ab est sed immemorabili. Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Quisque placerat facilisis egestas cillum dolore.<br>Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Quisque placerat facilisis egestas cillum dolore.</p>
</div>

app/views/static_pages/contact.html.erb
<%= render 'navbar' %>

<div class="green_ribbon animated fadeIn">
  <div class="text_wrapper_large">
    <p class="subheading">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
  </div>
</div>

<form action="" id="contact_form" class="animated fadeIn">
  <h4 class="contact_form_title">What's your name?</h3>
  <input type='text' placeholder='name' autofocus>
  <h4 class="contact_form_title">How can we reach you?</h3>
  <input type='email' placeholder='email'>
  <h4 class="contact_form_title">What can we do for you?</h3>
  <textarea placeholder='message'></textarea>
  <br>
  <input type='submit' value='send' id="send_button">
</form>

app/views/static_pages/homepage.html.erb
<div>
  <header class="header">
    <div id="homepage_navbar" class="animated fadeIn">
      <ul id="homepage_left_links" class="animated fadeInLeft">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Services', services_path %></li>
      </ul>
      <ul id="homepage_right_links" class="animated fadeInRight">
        <li><%= link_to 'Portfolio', portfolio_path %></li>
        <li><%= link_to 'Contact', new_contact_path %></li>
      </ul>
    </div>
    <div>
      <%= image_tag("scooter-logo-homepage.png", class: "animated fadeIn logo-homepage") %>
    </div>
  </header>
</div>

<div class="text_wrapper">
  <h1 class="homepage_headline animated fadeIn">Web Design to Grow Your Business</h1>
  <h2 class="homepage_secondline animated fadeIn">You work hard to build your business,<br> you website should work just as hard.</h2>
</div>

app/views/static_pages/portfolio.html.erb
<%= render 'navbar' %>

<div class="green_ribbon animated fadeIn">
  <div class="text_wrapper_large">
    <p class="subheading">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
  </div>
</div>

<div class="portfolio_example animated fadeIn" id="secure_inventory">
  <h4 class="portfolio_tag animated fadeIn">secure inventory</h4>
</div>
<div class="portfolio_example animated fadeIn" id="miracle_clean">
  <h4 class="portfolio_tag animated fadeIn">miracle clean</h4>
</div>
<div class="portfolio_example animated fadeIn" id="cindrich_boards">
  <h4 class="portfolio_tag animated fadeIn">cindrich boards</h4>
</div>

app/views/static_pages/services.html.erb
<%= render 'navbar' %>

<div class="green_ribbon animated fadeIn">
  <div class="text_wrapper_large">
    <p class="subheading"><strong>Web Design to Grow Your Business</strong><br>You work hard to build your business, your website should work just as hard.</p>
  </div>
</div>

<div class="service_wrapper animated fadeIn">
  <h3 class="service_title">Design</h3>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
</div>
<div class="service_wrapper animated fadeIn">
  <h3 class="service_title">SEO</h3>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
</div>
<div class="service_wrapper animated fadeIn">
  <h3 class="service_title">Redesign</h3>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
</div>
<div class="service_wrapper animated fadeIn" id="last_service">
  <h3 class="service_title">Maintenance</h3>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
    <p class="service_description">Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua.</p>
</div>